Feature/test api
rombaks/TaskManager pull request #14
Opened 2022-10-16 06:29 UTC by rombaks

Tests cover User, Task and Tag ViewSets.

2022-10-18 21:01 UTC, aleksandr-semenov-dbp requested changes

2022-10-18 21:01 UTC, aleksandr-semenov-dbp commented on tests/base_test_views.py
> +
нужен еще метод list() и, соответственно тестировать его.

2022-10-18 21:01 UTC, aleksandr-semenov-dbp commented on tests/test_tag.py
> +        expected_response = self.retrieve(id=id)
Нет, тут что-то все запуталось и мне это понять трудно. expected_response - это должен быть результат вызова метода expected_detail(), и его надо сравнивать с результатом вызова retreive(). Тоже самое далее

2022-10-19 19:59 UTC, rombaks commented on tests/base_test_views.py
> +
Спасибо. Добавил метод и тесты

2022-10-19 20:03 UTC, rombaks commented on tests/test_tag.py
> +        expected_response = self.retrieve(id=id)
Спасибо. Исправил путаницу. Теперь expected_response везде получает значение из метода expected_detail, либо expected_list.

2022-10-20 10:27 UTC, aleksandr-semenov-dbp requested changes

2022-10-20 10:27 UTC, aleksandr-semenov-dbp commented on tests/test_tag.py
> +        assert updated_tag == expected_response
Предыдущий метод правильно, а здесь снова немного не то. expected - это не должно быть результатом тестируемого метода, это то, что мы заранее знаем какой результатдолжен быть при правильной работе, нормально вычислять его здесь каким-нибудь своим тестовым методам expected_xxxx(). И его надо сравнить с тем что реально получилось при вызове метода. Проверять retrieve() здесь необязательно, достаточно проверить что возвращает update() (если это не какой-то хитрый случай с побочками)

2022-10-20 10:27 UTC, aleksandr-semenov-dbp commented on tests/test_tag.py
> +        expected_response = self.delete(tag["id"])
expected_response = ожидаемый_ответ, в данном случае это просто response

2022-10-20 12:03 UTC, rombaks commented on tests/test_tag.py
> +        assert updated_tag == expected_response
Спасибо за подробный фидбек. Исправил

2022-10-20 12:03 UTC, rombaks commented on tests/test_tag.py
> +        expected_response = self.delete(tag["id"])
Понял, спасибо. Переименовал

2022-10-20 12:08 UTC, aleksandr-semenov-dbp approved these changes

2022-10-20 12:33 UTC, merged